### PR TITLE
OpenBSD: prompt user to add their user to "staff" login class for performance improvement

### PR DESCRIPTION
**Pull request by Izder456**
What title says.

This PR prompts the user to add their account to the "staff" login class. If they agree, they're asked for their username, which is then confirmed. The script uses `auto-change-login-class` from https://github.com/outpaddling/auto-admin to assign the "staff" login class to the specified user.

### CODE REVIEW

**Comment by outpaddling** [comment]
This is a good idea, but it adding/modifying user accounts is not the purpose of desktop-installer.  User accounts aren't generally even created before running desktop-installer on a fresh install.  What we should do is modify auto-adduser to offer the staff group OpenBSD.  What is the list of groups that OpenBSD users commonly might be added to?

**Comment by outpaddling** [comment]
Try the latest auto-user-admin and auto-adduser from openbsd-wip/auto-admin.

**Comment by Izder456** [comment]
> While we're in there, what is the list of groups that OpenBSD users commonly might be added to?

- `_shutdown`: allows for passwordless `shutdown` command use. sometimes needed to turn off openbsd from desktop environment menus.

- `staff`: its not just a login class, its also a group. I am unsure what the group does, but I see users add themselves to it in addition to the class sometimes.

- `wheel`: goes without saying, its the only other group your user is in by default on a fresh openbsd install. the other is the usergoup sharing a name with your username.

**Comment by outpaddling** [comment]
Added a prompt for the _shutdown group on OpenBSD.  There doesn't seem to be anything special about the staff group (there are no files owned by staff on a fresh install).  Since both auto-adduser and the native adduser command allow the new user to be added to arbitrary groups, I did not add a prompt for that one.
I also added a comment to getting-started.md to suggest using the staff group.

**Pull request closed without merging**
